config/routes.rb
Rails.application.routes.draw do
  #---trainer related----#
  resources :trainers, only: [:new, :create]
  resources :login, only: [:new, :create]
  delete "logout", to: "login#destroy", as: "log_out"
  #-----Pokemons---------#
  resources :pokemons, only: [:index, :show]
  resources :pokeballs, only: [:index, :show, :new, :create, :destroy]
    
  #------Gym Leaders-----#
  resources :gymleaders, only: [:index, :show] do
    resources :badges, only: [:create, :index]
  end
 
  root :to => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :trainer
  belongs_to :gymleader

  validates_uniqueness_of :gymleader_id
end

app/models/gymleader.rb
class Gymleader < ApplicationRecord
    has_many :badges
    has_many :trainers, through: :badges
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :pokemon
  belongs_to :trainer

  validates_uniqueness_of :pokemon_id
  
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :pokeballs, dependent: :destroy
    has_many :trainers, through: :pokeballs

    def self.starters
        starters = [Pokemon.all[24], Pokemon.all[132], Pokemon.first, Pokemon.fourth, Pokemon.all[6]]
    end

    def poke_phrase
        ["Never give up!", "Put me in coach!", "I can't wait to battle!", "Please give me belly rubs", "Why won't you love me??", "Mod2izfun"].sample
    end

end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :badges, dependent: :destroy
    has_many :gymleaders, through: :badges

    has_many :pokeballs, dependent: :destroy
    has_many :pokemons, through: :pokeballs

    validates_presence_of :username
    validates_uniqueness_of :username

    def total_badges
        0 + self.badges.count
    end

    def total_pokemons
        0 + self.pokeballs.count
    end

    def can_catch_pokemon
        self.total_badges >= self.total_pokemons
    end

    def can_battle
       !self.can_catch_pokemon
    end

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :setup_notifications, :setup_authorizations

    def setup_notifications
        @errors = flash[:errors]
        @notification = flash[:notification]
    end

    def setup_authorizations
        @logged_in = logged_in?
        @logged_in_trainer = Trainer.find(current_trainer_id) if logged_in?
        @can_catch_pokemon = logged_in? && @logged_in_trainer.can_catch_pokemon
    end

    private

    def log_out_trainer!
        session.delete(:trainer_id)
    end

    def log_in_trainer(trainer_id)
        session[:trainer_id] = trainer_id
    end

    def logged_in?
        !!current_trainer_id
    end

    def current_trainer_id
        session[:trainer_id]
    end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
    def index
        @badges = @logged_in_trainer.badges
    end

    def create
        unless logged_in?
            flash[:notification] = "Please Log in first, unknown trainer!"
            return redirect_to new_login_path
        end


        if @logged_in_trainer.can_battle
            @badge = Badge.create(trainer_id: current_trainer_id, gymleader_id: params[:gymleader_id])
            if !@badge.valid?
                flash[:notification] = "You've already received this Gym Badge."
                redirect_to pokeballs_path
            else
                flash[:notification] = "Congratulations on defeating #{@badge.gymleader.name}!"
                redirect_to pokeballs_path
            end
        else
            flash[:notification] = "You don't have enough Pokemon to battle this Gym Leader. Add a Pokemon to your party."
            redirect_to root_path
        end
    end
end

app/controllers/gymleaders_controller.rb
class GymleadersController < ApplicationController

    def index
        if request.path != gymleaders_path
            redirect_to gymleaders_path
        end
        @gymleaders = Gymleader.includes(:badges).all
    end

    def show
        @gymleader = Gymleader.find(params[:id])
    end
    
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def new
    end

    def create
        @trainer = Trainer.find_by(username: params[:username])
        if @trainer && @trainer.authenticate(params[:password])
            log_in_trainer @trainer.id
            redirect_to root_path
        else
            flash[:errors] = [ "We don't have a trainer with that username and password"]
            redirect_to new_login_path
        end
    end

    def destroy
        log_out_trainer!
        redirect_to root_path
    end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController
    

    def index
        @pokeballs = @logged_in_trainer.pokeballs
        @badges = @logged_in_trainer.badges
    end

    def new
        @pokeball = Pokeball.new
    end

    def create
        unless logged_in?
            flash[:notification] = "Please Log in first, unknown trainer!"
            return redirect_to new_login_path
        end

        if @can_catch_pokemon
            @pokeball = Pokeball.create(trainer_id: current_trainer_id, pokemon_id: params[:pokeball][:pokemon_id])
        else
            flash[:notification] = "You need more badges to get more pokemon!"
        end
        redirect_to root_path
    end
    
    def destroy
        @pokeball = Pokeball.find(params[:id])
        @pokeball.destroy
        redirect_to pokeballs_path
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

    def index
        if request.path != pokemons_path
            redirect_to pokemons_path
        end
        @pokemons = Pokemon.includes(:pokeballs).all
    end

    def show
        @pokemon = Pokemon.find(params[:id])
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    def new
        @trainer = Trainer.new
    end
    
    def create
        @trainer = Trainer.create(trainer_params)
        if @trainer.valid?
            log_in_trainer @trainer.id
            redirect_to root_path
        else
            flash[:errors] = @trainer.errors.full_messages
            redirect_to new_trainer_path
        end
    end

    private
    
    def trainer_params
        params.require(:trainer).permit(:username, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :get_me_trainers

    def index
        @trainers = Trainer.all
    end

    def show
    end

    private

    def get_me_trainers
        @trainers = Trainer.all
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gymleaders_helper.rb
module GymleadersHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pokeballs_helper.rb
module PokeballsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/badges/index.html.erb
<style>
    h1{
        color:black;
    }

</style>


<h1>Congratulations! Here are the Badges that prove your Victory!</h1>

<ul>
<% @badges.each do |badge|%>
    <li>You've gotten the <%= badge.gymleader.badge_name%>!</li>
    <img src="<%=badge.gymleader.badge_img%>">
<% end %>
</ul>

app/views/gymleaders/index.html.erb
<style>
body {
    background-image: url('/gymleader_index/kantogymleaders.jpg');
    background-size: cover;
}
.gymleader_hover:hover{
}

</style>
<ul>
    <% @gymleaders.each do |gymleader| %>
        <li><img src= <%=gymleader.headshot%> class="gymleader_hover">
        <br>
        <%= button_to gymleader.name, gymleader_path(gymleader), method: "get"%>
        </li>
    <% end %>
</ul>

app/views/gymleaders/show.html.erb
<style>
body {
    background-image: url('<%= @gymleader.bg.to_s%>');
    background-size: cover;
  }
  h2{
    color: black;
    background-color: white;
    opacity: 60%;
    margin: auto;
  }
  h3{
    color: black;
    background-color: white;
    opacity: 60%;
  }

  h4{
    color: black;
    background-color: white;
    opacity: 50%;
  }

  button{

  }
</style>

<h2>You have entered the <%= @gymleader.city %> Gym!</h2>

<div class ="coolshit">
<img src=<%= @gymleader.sprite %> alt="sprite goes here">
=> <img src=<%=@gymleader.fullbody %> alt="fullbody here">
=> <img src=<%= @gymleader.portrait %> alt="portrait here">
</div>



<h3><%= @gymleader.name%> is the leader of this gym!</h3>

<h4>All trainers who defeat this gym leader will receive the <%= @gymleader.badge_name %></h4>
    <h4>BATTLE <%=@gymleader.name%>! </h4>


  <%= form_for [@gymleader, Badge.new], local:true do |f|%>
    <button type="submit" class='<%= @can_battle ? "Battle" : "Cannot Battle"%>'>
      
    
    </button>
  <% end %>


<img src=<%= @gymleader.badge_img %> alt="badge thingy" class="badge_img">
<%=button_to "Return to Gym Leaders", gymleaders_path, method: :get%>

app/views/login/new.html.erb
<h1>Welcome back to the Kanto Region!</h1>

<%= form_tag login_index_path do %>
    <ul>
        <li>
            <%= label_tag :username %>
            <%= text_field_tag :username %>
        </li>

        <li>
            <%= label_tag :password %>
            <%= password_field_tag :password %>
        </li>
    </ul>

    <%= submit_tag "Log in" %>
<% end %>

app/views/pokeballs/_form.html.erb
<!-- Starter Pokemon Form-->

 <style>
        body{
            background-image: url("/pokemonbackgrounds/startersall.jpg");
            background-size: 100%;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        img{
          opacity: 80%;

        }

        h2{
          color: black;
        }
    </style>




  <img class="one" src = "/pokemonbackgrounds/pickstarter.gif">
<%= form_for @pokeball do |f|%>
    <h2><%= f.label "Pick your Starter Pokemon" %></h2>
  
  <h2>  <%= f.collection_radio_buttons :pokemon_id, Pokemon.starters, :id, :name %> </h2> 

    <ul class="move_sprite">
    <% Pokemon.starters.each do |starter|%>
        <li class="starter_sprite_form"><img src=<%= starter.sprite %>></li>
    <%end%>
    </ul>

    <%= f.submit value="Choose Starter"%>
    
<% end %>

app/views/pokeballs/_form2.html.erb
<!-- Regular Pokemon Form-->
 <style>
body {
    background-image: url('/pokemonbackgrounds/bulbzlowspeed.gif');
    background-size: 100%;
   
}

h3{
  position: relative; 
	top: 39px;
	right: 490px;
  color:black;
  margin-left:auto;
}
.gymleader_hover:hover{
}

</style>
 
 
 
 
<%= form_for @pokeball do |f| %>

<h3>  Pokemon List Select:</h3> <%=f.collection_select :pokemon_id, Pokemon.all, :id, :name %> 
    
    <%= f.submit value: "Catch Pokemon!" %>
<% end %> </label>

app/views/pokeballs/index.html.erb
<h1>Welcome Fellow Pokemon Trainer!</h1>

<style>
body{
        background-image: url('/pokemonbackgrounds/trainershow.jpg');
        background-size: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
h1{
    color:black;
}
h2{
    color:black;
}

h4{
    color:black;
}

.badge{
    margin: 10px;
    width: 100px;
}


</style>
    <h2><%="#{@logged_in_trainer.username}'s party"%></h2>
<ul>
    <% if @logged_in_trainer.total_pokemons > 0 %>

        <% @pokeballs.each do |pokeball| %>
            <li>
                <img src=<%= pokeball.pokemon.sprite %>>
                <% if @logged_in_trainer.id == pokeball.trainer_id %>
                <%= button_to "Release Pokemon", pokeball_path(pokeball), method: :delete %>
                <% end %>
            </li>
        <% end %>
    <% else %>
        <h4>You can't go on your journey alone! You need to go get a starter Pokemon from Prof. Oak!</h3><br>
        <li><%= button_to "Choose My Starter Pokemon", new_pokeball_path, method: :get %></li>
    <% end %>
</ul>

<ul>
    <% @badges.each do |badge|%>
      <img class="badge" src="<%= badge.gymleader.badge_img %>"><br>
    <%end%>
</ul>

app/views/pokeballs/new.html.erb
<style>
    h1{
        color:black;
    }
</style>

<h1>Gotta Catch 'Em All!</h1>

<% if @logged_in_trainer.total_pokemons > 0 %>
    <%= render "form2"%>
<% else %>
    <%=render "form"%>
<% end %>

app/views/pokemons/index.html.erb
    <style>
        body{
            background-image: url("/pokemonbackgrounds/allpokemon.png");
            background-size: 100%;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

    </style>

<div class="pokemon-tile">
    <ol><% @pokemons.each do |pokemon| %>
       <li> <img class="img-center" src=<%=pokemon.sprite%>>
        <%= button_to pokemon.name, pokemon_path(pokemon), method: :get%>
        
        </li>
    <% end %>
    
    </ol>
</div>

app/views/pokemons/show.html.erb
<style>
    body{
        background-image: url('<%= @pokemon.background.to_s%>');
        background-size: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
    
    h3{
        color: black;
    }
</style>
    <br>
    <%= button_to "Catch a pokemon!", new_pokeball_path, method: :get %>
    <br>

<div class="text-align-container">
    <img src=<%= @pokemon.big_img %> alt="Picture goes here">

    <h3 id="electric"> My name is <%= @pokemon.name %> </h3>

    <h3> My type(s) are: <%= @pokemon.poke_type%> </h3>

    <h3> My favorite move is: <%= @pokemon.attack%></h3>

    <h3> <%= @pokemon.poke_phrase%></h3>
</div>

<p><%= button_to "Back to Pokedex", pokemons_path, method: :get%></p>

app/views/trainers/new.html.erb
<style>
.no_center{
    text-align: left; 
}

.starter_sprite_form{ 
   margin: 0px 10px 0px 10px;
}

.move_sprite{
    margin-left: 140px;
}
</style>

<h1>Congratulations on beginning your new pokemon journey!</h1>

<div class="no_center">
    <%= form_for @trainer do |f|%>
        <ul>
            <li>
                <%= f.label :username %>
                <%= f.text_field :username %>
            </li>

            <li>
                <%= f.label :password %>
                <%= f.password_field :password %>
            </li>
        </ul>
        <%= f.submit %>
    <% end %>
</div>

app/views/welcome/index.html.erb
<head>
<style>
.center{
    display: block;
    margin-left: auto;
    margin-right: auto;
    top: 100px;
}

h1{
    color: black;
}
body{
        background-image: url('/pokemonbackgrounds/pokemonwelcome.jpg');
        background-size: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
       
    }

</style>
</head>

<body>
<img src="/welcome_images/poke-logo.png" alt="pokemon logo" class="center">

<h1>Welcome to the PokeProjectAppMon!</h1>

<%# <img src="https://dev-to-uploads.s3.amazonaws.com/i/fgrgc3ixvzg7rym32v3z.gif" alt="snorlax goes here"> %>




</body>