config/routes.rb
Rails.application.routes.draw do
  #---trainer related----#
  resources :trainers, only: [:new, :create]
  resources :login, only: [:new, :create]
  delete "logout", to: "login#destroy", as: "log_out"
  #-----Pokemons---------#
  resources :pokemons, only: [:index, :show]
  resources :pokeballs, only: [:index, :show, :new, :create, :destroy]
    
  #------Gym Leaders-----#
  resources :gymleaders, only: [:index, :show] do
    resources :badges, only: [:create, :index]
  end
 
  root :to => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :trainer
  belongs_to :gymleader

  validates_uniqueness_of :gymleader_id
end

app/models/gymleader.rb
class Gymleader < ApplicationRecord
    has_many :badges
    has_many :trainers, through: :badges
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :pokemon
  belongs_to :trainer

  validates_uniqueness_of :pokemon_id
  
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :pokeballs, dependent: :destroy
    has_many :trainers, through: :pokeballs

    def self.starters
        starters = [Pokemon.all[24], Pokemon.all[132], Pokemon.first, Pokemon.fourth, Pokemon.all[6]]
    end

    def poke_phrase
        ["Never give up!", "Put me in coach!", "I can't wait to battle!", "Please give me belly rubs", "Why won't you love me??", "Mod2izfun"].sample
    end

end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :badges, dependent: :destroy
    has_many :gymleaders, through: :badges

    has_many :pokeballs, dependent: :destroy
    has_many :pokemons, through: :pokeballs

    validates_presence_of :username
    validates_uniqueness_of :username

    def total_badges
        0 + self.badges.count
    end

    def total_pokemons
        0 + self.pokeballs.count
    end

    def can_catch_pokemon
        self.total_badges >= self.total_pokemons
    end

    def can_battle
       !self.can_catch_pokemon
    end

    has_secure_password
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
    def index
        @badges = @logged_in_trainer.badges
    end

    def create
        unless logged_in?
            flash[:notification] = "Please Log in first, unknown trainer!"
            return redirect_to new_login_path
        end


        if @logged_in_trainer.can_battle
            @badge = Badge.create(trainer_id: current_trainer_id, gymleader_id: params[:gymleader_id])
            if !@badge.valid?
                flash[:notification] = "You've already received this Gym Badge."
                redirect_to pokeballs_path
            else
                flash[:notification] = "Congratulations on defeating #{@badge.gymleader.name}!"
                redirect_to pokeballs_path
            end
        else
            flash[:notification] = "You don't have enough Pokemon to battle this Gym Leader. Add a Pokemon to your party."
            redirect_to root_path
        end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def new
    end

    def create
        @trainer = Trainer.find_by(username: params[:username])
        if @trainer && @trainer.authenticate(params[:password])
            log_in_trainer @trainer.id
            redirect_to root_path
        else
            flash[:errors] = [ "We don't have a trainer with that username and password"]
            redirect_to new_login_path
        end
    end

    def destroy
        log_out_trainer!
        redirect_to root_path
    end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController
    

    def index
        @pokeballs = @logged_in_trainer.pokeballs
        @badges = @logged_in_trainer.badges
    end

    def new
        @pokeball = Pokeball.new
    end

    def create
        unless logged_in?
            flash[:notification] = "Please Log in first, unknown trainer!"
            return redirect_to new_login_path
        end

        if @can_catch_pokemon
            @pokeball = Pokeball.create(trainer_id: current_trainer_id, pokemon_id: params[:pokeball][:pokemon_id])
        else
            flash[:notification] = "You need more badges to get more pokemon!"
        end
        redirect_to root_path
    end
    
    def destroy
        @pokeball = Pokeball.find(params[:id])
        @pokeball.destroy
        redirect_to pokeballs_path
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

    def index
        if request.path != pokemons_path
            redirect_to pokemons_path
        end
        @pokemons = Pokemon.includes(:pokeballs).all
    end

    def show
        @pokemon = Pokemon.find(params[:id])
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    def new
        @trainer = Trainer.new
    end
    
    def create
        @trainer = Trainer.create(trainer_params)
        if @trainer.valid?
            log_in_trainer @trainer.id
            redirect_to root_path
        else
            flash[:errors] = @trainer.errors.full_messages
            redirect_to new_trainer_path
        end
    end

    private
    
    def trainer_params
        params.require(:trainer).permit(:username, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :get_me_trainers

    def index
        @trainers = Trainer.all
    end

    def show
    end

    private

    def get_me_trainers
        @trainers = Trainer.all
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gymleaders_helper.rb
module GymleadersHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pokeballs_helper.rb
module PokeballsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeProjectAppMon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css'>
  </head>
  <style>
  .logout_button{
    margin-left: 685px;

  }

  header{
    background-color: grey;
    opacity: 70%;
    color: black;
  }
  </style>

  <body>
    <header>
      <% if @logged_in %>
        <%= link_to "Home Page", root_path %> |
        <%= link_to "View Pokedex", pokemons_path %> |
        <%= link_to "Gyms", gymleaders_path %> | <br>
        Welcome back, Trainer <%= @logged_in_trainer.username %>!<br>
        <%= link_to "Trainer Profile", pokeballs_path%>
        
        Badges: <%= @logged_in_trainer.total_badges %>
        Pokemons: <%= @logged_in_trainer.total_pokemons %>
        <%= button_to "Log out", log_out_path, :class => "logout_button" , method: :delete %>

      <% else %>
        <%= link_to "Login Trainer", new_login_path %> |
        <%= link_to "Register New Trainer", new_trainer_path %>
      <% end %>

      <% if @notification %> 
        <p class="message">
          <%= @notification %>
        </p>
      <% end %>

      <% if @errors && @errors.any? %>
      <ul class="errors">
        <% @errors.each do |error| %>
        <li>
          <%= error %>
        </li>
        <% end %>
      </ul>
      <% end %>
    <hr>
    </header>

    <%= yield %>
  </body>
</html>